# pyre-strict

DEFAULT_INITIAL_MAX_TOKEN: int = 512
DEFAULT_MAX_MAX_TOKEN: int = 16384

AWS_CLOUD_ACCOUNT_ID = "009160068926"
GOOGLE_CLOUD_PROJECT_ID = "confucius-gcp-dev-xgmwf"
GOOGLE_CLOUD_ROLE = "sso-view-only"
GOOGLE_CLOUD_LOCATION = "global"
AZURE_OPENAI_API_KEY_SECRET_NAME = "PRIMARY_KEY"
AZURE_OPENAI_HOST_SECRET_NAME = "HOST"

AZURE_OPENAI_SECRET_GROUPS = {
    "o3": "AZ_NET_ENG_EASTUS2N3_DEFAULT",
    "o4-mini": "AZ_NET_ENG_EASTUS2N2_DEFAULT",
    "gpt-5": "AZ_NET_ENG_EASTUS2N5_DEFAULT",
}

AZURE_OPENAI_API_VERSION = "2025-04-01-preview"
AZURE_OPENAI_FWD_PROXY = "http://fwdproxy:8080"
AZURE_OPENAI_MODEL_PREFIXES = ["gpt", "o1", "o3", "o4"]
FB_CA_BUNDLE = "/var/facebook/rootcanal/ca.pem"
FWDPROXY_PORT = 8082
FWDPROXY_HOSTNAME = "https://fwdproxy"

FWDPROXY_URL = f"{FWDPROXY_HOSTNAME}:{FWDPROXY_PORT}"
FWD_PROXIES: dict[str, str] = {"https": FWDPROXY_URL, "http": FWDPROXY_URL}
